[package]
name = "servo-webmidi-traits"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "webmidi_traits"
path = "lib.rs"

[dependencies]
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
midir = { workspace = true }
profile_traits = { workspace = true }
serde = { workspace = true }
servo-base = { workspace = true }
servo-url = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
